// Ingredient references audited against the 150 recorded recipes, 2026-09-30.
// IDs below are authored constants: never regenerate IDs when renaming or adding records.
// These are recipe references, not verified sensory encodings or shop inventory.
(() => {
  const DATA = window.FLAVOR_ATLAS_DATA;
  if (!DATA?.cocktails || !DATA?.ingredients) return;
  const normalize = value => String(value || '').normalize('NFKC').replace(/’/g, "'").trim().replace(/\s+/g, ' ').toLowerCase();
  // [id, display name, catalog category, aliases, specific unresolved detail]
  const REFERENCES = [
    ["ING-0025", "Umeshu bitters", "Bitters", [], "Kept separate from Umeshu Tincture; the recipes use both labels and do not establish equivalence."],
    ["ING-0026", "Saline", "Seasoning", [], "Concentration is not recorded. Confirm the house dilution before comparing doses."],
    ["ING-0027", "Cucumber juice", "Juice / Nectar", [], ""],
    ["ING-0028", "Simple syrup", "Sweetener", ["Simple Syrup", "Sugar Syrup"], ""],
    ["ING-0029", "Grey Goose Berry Rouge", "Vodka", [], ""],
    ["ING-0030", "Triple sec", "Liqueur", ["Triple Sec"], ""],
    ["ING-0031", "Monkey 47 Gin", "Gin", [], ""],
    ["ING-0032", "Cocchi Americano", "Aromatized Wine", [], ""],
    ["ING-0033", "Amaro Montenegro", "Amaro", ["Montenegro"], ""],
    ["ING-0034", "Orange bitters", "Bitters", ["Orange Bitters"], ""],
    ["ING-0035", "Metaxa 7 Star", "Aged Grape Spirit", [], ""],
    ["ING-0036", "Peychaud’s Bitters", "Bitters", ["Peychaud's bitters"], ""],
    ["ING-0037", "Mandarin orange bitters", "Bitters", [], ""],
    ["ING-0038", "Ouzo", "Anise Spirit", [], ""],
    ["ING-0039", "Suntory Toki", "Whiskey", [], ""],
    ["ING-0040", "Grapefruit bitters", "Bitters", ["Grapefruit Bitters"], ""],
    ["ING-0041", "Cognac", "Brandy", [], ""],
    ["ING-0042", "Dark Crème de Cacao", "Liqueur", ["Brown Crème de Cacao"], ""],
    ["ING-0043", "Fresh Cream", "Egg / Dairy", ["Fresh Cream, chilled"], ""],
    ["ING-0044", "Campari", "Aperitivo", ["Bitter Campari"], ""],
    ["ING-0045", "Sweet Red Vermouth", "Aromatized Wine", [], ""],
    ["ING-0046", "Soda Water", "Mixer", [], ""],
    ["ING-0047", "Gin", "Gin", [], ""],
    ["ING-0048", "Apricot Brandy", "Liqueur", [], ""],
    ["ING-0049", "Calvados", "Brandy", [], ""],
    ["ING-0050", "Maraschino Luxardo", "Liqueur", [], ""],
    ["ING-0051", "Crème de Violette", "Liqueur", [], ""],
    ["ING-0052", "White Rum", "Rum", [], ""],
    ["ING-0053", "Bourbon Whiskey", "Whiskey", [], ""],
    ["ING-0054", "Rye Whiskey", "Whiskey", [], ""],
    ["ING-0055", "Brandy", "Brandy", [], ""],
    ["ING-0056", "Curaçao", "Liqueur", [], ""],
    ["ING-0057", "Aromatic Bitters", "Bitters", [], ""],
    ["ING-0058", "Old Tom Gin", "Gin", [], ""],
    ["ING-0059", "Raspberry Syrup", "Syrup / Cordial", [], ""],
    ["ING-0060", "Egg White", "Egg / Dairy", ["Egg White (optional)", "Egg White, optional"], ""],
    ["ING-0061", "White Cuban Rum", "Rum", [], ""],
    ["ING-0062", "Superfine Sugar", "Sweetener", [], ""],
    ["ING-0063", "Dry Vermouth", "Aromatized Wine", [], ""],
    ["ING-0064", "London Dry Gin", "Gin", [], ""],
    ["ING-0065", "Fernet", "Amaro", [], ""],
    ["ING-0066", "Green Chartreuse", "Liqueur", [], ""],
    ["ING-0067", "Angostura Bitters", "Bitters", [], ""],
    ["ING-0068", "Pineapple Juice", "Juice / Nectar", ["Fresh Pineapple Juice"], ""],
    ["ING-0069", "Grenadine Syrup", "Syrup / Cordial", [], ""],
    ["ING-0070", "Dry Gin", "Gin", [], ""],
    ["ING-0071", "Fresh Orange Juice", "Juice / Nectar", ["Orange Juice"], ""],
    ["ING-0072", "Absinthe", "Anise Spirit", [], ""],
    ["ING-0073", "Sugar", "Sweetener", [], ""],
    ["ING-0074", "Water", "Mixer", [], ""],
    ["ING-0075", "Jamaican Rum", "Rum", [], ""],
    ["ING-0076", "Sugar Cane Juice", "Juice / Nectar", [], ""],
    ["ING-0077", "Red Tawny Port", "Fortified Wine", [], ""],
    ["ING-0078", "Egg Yolk", "Egg / Dairy", [], ""],
    ["ING-0079", "Cream", "Egg / Dairy", [], ""],
    ["ING-0080", "Orange Flower Water", "Aromatic", ["Orange Blossom Water"], ""],
    ["ING-0081", "Vanilla Extract", "Aromatic", [], ""],
    ["ING-0082", "Sweet Vermouth", "Aromatized Wine", [], ""],
    ["ING-0083", "Cherry Brandy Luxardo", "Liqueur", [], ""],
    ["ING-0084", "Scotch Whisky", "Whiskey", [], ""],
    ["ING-0085", "Drambuie", "Liqueur", [], ""],
    ["ING-0086", "White Crème de Menthe", "Liqueur", [], ""],
    ["ING-0087", "Bénédictine", "Liqueur", ["DOM Bénédictine"], ""],
    ["ING-0088", "Prosecco", "Sparkling Wine", [], ""],
    ["ING-0089", "White Peach Purée", "Fruit / Purée", [], ""],
    ["ING-0090", "Vodka", "Vodka", [], ""],
    ["ING-0091", "Coffee Liqueur", "Liqueur", [], ""],
    ["ING-0092", "Tomato Juice", "Juice / Nectar", [], ""],
    ["ING-0093", "Worcestershire Sauce", "Seasoning", [], ""],
    ["ING-0094", "Tabasco", "Seasoning", [], ""],
    ["ING-0095", "Celery Salt", "Seasoning", [], ""],
    ["ING-0096", "Pepper", "Seasoning", [], ""],
    ["ING-0097", "Cachaça", "Cane Spirit", [], ""],
    ["ING-0098", "Lime", "Fruit / Purée", ["Lime, cut into wedges"], ""],
    ["ING-0099", "White Cane Sugar", "Sweetener", [], ""],
    ["ING-0100", "Champagne", "Sparkling Wine", ["Chilled Champagne"], ""],
    ["ING-0101", "Grand Marnier", "Liqueur", ["Grand Marnier (optional)"], ""],
    ["ING-0102", "Cointreau", "Liqueur", [], ""],
    ["ING-0103", "Vodka Citron", "Vodka", [], ""],
    ["ING-0104", "Cranberry Juice", "Juice / Nectar", [], ""],
    ["ING-0105", "Cola", "Mixer", [], ""],
    ["ING-0106", "Amaretto", "Liqueur", [], ""],
    ["ING-0107", "White Crème de Cacao", "Liqueur", [], ""],
    ["ING-0108", "Green Crème de Menthe", "Liqueur", [], ""],
    ["ING-0109", "Rum", "Rum", [], ""],
    ["ING-0110", "Grapefruit Juice", "Juice / Nectar", [], ""],
    ["ING-0111", "Ginger Ale", "Mixer", [], ""],
    ["ING-0112", "Irish Whiskey", "Whiskey", [], ""],
    ["ING-0113", "Hot Coffee", "Coffee", [], ""],
    ["ING-0114", "Dry White Wine", "Wine", [], ""],
    ["ING-0115", "Crème de Cassis", "Liqueur", [], ""],
    ["ING-0116", "Tequila", "Agave Spirit", [], ""],
    ["ING-0117", "Amber Jamaican Rum", "Rum", [], ""],
    ["ING-0118", "Martinique Molasses Rhum", "Rum", [], ""],
    ["ING-0119", "Orange Curaçao", "Liqueur", [], ""],
    ["ING-0120", "Orgeat Syrup", "Syrup / Cordial", ["Orgeat"], ""],
    ["ING-0121", "100% Agave Tequila", "Agave Spirit", [], ""],
    ["ING-0122", "Mint", "Herb / Spice", ["Fresh Mint", "Mint Leaves"], ""],
    ["ING-0123", "Powdered Sugar", "Sweetener", [], ""],
    ["ING-0124", "Ginger Beer", "Mixer", [], ""],
    ["ING-0125", "Coconut Cream", "Cream", [], ""],
    ["ING-0126", "Pisco", "Grape Spirit", [], ""],
    ["ING-0127", "Cynar", "Amaro", [], ""],
    ["ING-0128", "Peach Schnapps", "Liqueur", [], ""],
    ["ING-0129", "Cherry Sangue Morlacco", "Liqueur", [], ""],
    ["ING-0130", "Jamaican Dark Rum", "Rum", [], ""],
    ["ING-0131", "Gold Puerto Rican Rum", "Rum", [], ""],
    ["ING-0132", "Demerara Rum", "Rum", [], ""],
    ["ING-0133", "Falernum", "Syrup / Cordial", [], "Recipe does not specify a brand or whether this is alcoholic; kept separate from Velvet Falernum."],
    ["ING-0134", "Donn’s Mix", "House Preparation", [], ""],
    ["ING-0135", "Pernod", "Anise Spirit", [], ""],
    ["ING-0136", "Crème de Mûre", "Liqueur", [], ""],
    ["ING-0137", "Cuban Aguardiente", "Cane Spirit", [], ""],
    ["ING-0138", "Raw Honey", "Sweetener", [], ""],
    ["ING-0139", "Goslings Rum", "Rum", [], ""],
    ["ING-0140", "Gold Jamaican Rum", "Rum", [], ""],
    ["ING-0141", "Cuban Rum", "Rum", [], ""],
    ["ING-0142", "Passion Fruit Syrup", "Syrup / Cordial", [], ""],
    ["ING-0143", "Kahlúa", "Liqueur", [], ""],
    ["ING-0144", "Espresso", "Coffee", ["Fresh Espresso"], ""],
    ["ING-0145", "Fernet Branca", "Amaro", [], ""],
    ["ING-0146", "Raspberry Liqueur", "Liqueur", [], ""],
    ["ING-0147", "Italian Basil", "Herb / Spice", [], ""],
    ["ING-0148", "Havana Club Ron Profundo", "Rum", [], ""],
    ["ING-0149", "Havana Club Ron Smoky", "Rum", [], ""],
    ["ING-0150", "Frangelico", "Liqueur", [], ""],
    ["ING-0151", "Passion Fruit Purée", "Fruit / Purée", ["Passion Fruit Puree"], ""],
    ["ING-0152", "Ginger", "Herb / Spice", ["Fresh Ginger"], ""],
    ["ING-0153", "Espadin Mezcal", "Agave Spirit", [], ""],
    ["ING-0154", "Jamaica Overproof White Rum", "Rum", [], ""],
    ["ING-0155", "Blackstrap Rum", "Rum", [], ""],
    ["ING-0156", "Demerara Sugar Syrup", "Sweetener", [], ""],
    ["ING-0157", "Peach Brandy", "Liqueur", [], ""],
    ["ING-0158", "Honey Mix", "Sweetener", [], ""],
    ["ING-0159", "Pineapple Chunks", "Fruit / Purée", [], ""],
    ["ING-0160", "Mezcal", "Agave Spirit", [], ""],
    ["ING-0161", "Aperol", "Aperitivo", [], ""],
    ["ING-0162", "Shiraz Red Wine", "Wine", [], ""],
    ["ING-0163", "Malbec Red Wine", "Wine", [], ""],
    ["ING-0164", "Aged Rum", "Rum", [], ""],
    ["ING-0165", "Brut Champagne", "Sparkling Wine", [], ""],
    ["ING-0166", "Salt", "Seasoning", [], ""],
    ["ING-0167", "Pink Grapefruit Soda", "Mixer", [], ""],
    ["ING-0168", "Blended Scotch Whisky", "Whiskey", [], ""],
    ["ING-0169", "Lagavulin 16", "Whiskey", [], ""],
    ["ING-0170", "Cloves", "Herb / Spice", [], ""],
    ["ING-0171", "Vanilla Vodka", "Vodka", [], ""],
    ["ING-0172", "Passion Fruit Liqueur", "Liqueur", [], ""],
    ["ING-0173", "Vanilla Sugar", "Sweetener", [], ""],
    ["ING-0174", "Sparkling Wine", "Sparkling Wine", [], ""],
    ["ING-0175", "Amontillado Sherry", "Fortified Wine", [], ""],
    ["ING-0176", "Palo Cortado", "Fortified Wine", [], ""],
    ["ING-0177", "Orange", "Fruit / Purée", [], ""],
    ["ING-0178", "Lemon", "Fruit / Purée", [], ""],
    ["ING-0179", "Elderflower Cordial", "Syrup / Cordial", [], ""],
    ["ING-0180", "Red Chili Pepper", "Herb / Spice", [], ""],
    ["ING-0181", "Rhum Martinique Agricole", "Rum", [], ""],
    ["ING-0182", "Blended Aged Rum", "Rum", [], ""],
    ["ING-0183", "Allspice Dram", "Liqueur", [], ""],
    ["ING-0184", "Agave Nectar", "Sweetener", [], ""],
    ["ING-0185", "White Smooth Grappa", "Grape Spirit", [], ""],
    ["ING-0186", "Chamomile Honey Mix", "Syrup / Cordial", [], ""],
    ["ING-0187", "Chamomile Cordial", "Syrup / Cordial", [], ""],
    ["ING-0188", "Mastiha", "Liqueur", [], "Generic recipe label; brand is not specified. Kept separate from Antica and Skinos."],
    ["ING-0189", "Blood Orange Juice", "Juice / Nectar", [], ""],
    ["ING-0190", "Orange Liqueur", "Liqueur", [], ""],
    ["ING-0191", "Stoli Citrus", "Vodka", [], ""],
    ["ING-0192", "Olive Brine", "Seasoning", [], ""],
    ["ING-0193", "Hot Sauce", "Seasoning", [], ""],
    ["ING-0194", "Dried Oregano", "Herb / Spice", [], ""],
    ["ING-0195", "White Bitter Rouge", "Aperitivo", [], "Exact product identity needs confirmation from the bottle or house specification."],
    ["ING-0196", "Thyme Blossom Tincture", "Tincture", [], ""],
    ["ING-0197", "Foro Amaro", "Amaro", [], ""],
    ["ING-0198", "Velvet Falernum", "Liqueur", [], ""],
    ["ING-0199", "Skinos Mastiha", "Liqueur", [], ""],
    ["ING-0200", "Elixir Liqueur", "Liqueur", [], "Exact product identity needs confirmation from the bottle or house specification."],
    ["ING-0201", "Del Maguey Vida", "Agave Spirit", [], ""],
    ["ING-0202", "Fruitful Blue Raspberry Lemonade", "Juice / Nectar", [], ""],
    ["ING-0203", "Knob Creek Bourbon", "Whiskey", [], ""],
    ["ING-0204", "Starlight Applejack", "Apple Brandy", [], ""],
    ["ING-0205", "Bauchant", "Liqueur", [], ""],
    ["ING-0206", "Peach Bitters", "Bitters", [], ""],
    ["ING-0207", "Lychee Syrup", "Syrup / Cordial", [], ""],
    ["ING-0208", "Grenadine", "Syrup / Cordial", [], ""],
    ["ING-0209", "Metaxa", "Aged Grape Spirit", [], "Star expression is not specified in these recipes; kept separate from 7 Star and 12 Star."],
    ["ING-0210", "Concentrated Nescafé Frappé", "Coffee", [], ""],
    ["ING-0211", "Chocolate Bitters", "Bitters", [], ""],
    ["ING-0212", "Cadilla Açaí Liqueur", "Liqueur", [], "Product spelling and identity are preserved from the recipe and need confirmation."],
    ["ING-0213", "Feta-Brine Ice", "House Preparation", [], "Preparation ratios are not recorded; kept separate from the lactic-acid ice and feta-piece cube."],
    ["ING-0214", "Pistachio Orgeat", "Syrup / Cordial", [], ""],
    ["ING-0215", "Heavy Cream", "Egg / Dairy", [], ""],
    ["ING-0216", "Thyme Blossom Honey Syrup", "Syrup / Cordial", [], ""],
    ["ING-0217", "Vanilla Gelato", "Egg / Dairy", [], ""],
    ["ING-0218", "Galliano", "Liqueur", [], ""],
    ["ING-0219", "Prickly Pear", "Fruit / Purée", [], "Preparation is not specified: confirm whether this is juice, purée, syrup, or another product."],
    ["ING-0220", "Cream Cheese Tincture", "Tincture", [], "House preparation formula is not recorded; the recipe label is preserved."],
    ["ING-0221", "Black Cherry Tincture", "Tincture", [], ""],
    ["ING-0222", "Soho Lychee Liqueur", "Liqueur", [], ""],
    ["ING-0223", "Umeshu Tincture", "Tincture", [], ""],
    ["ING-0224", "Pineapple Syrup", "Syrup / Cordial", [], ""],
    ["ING-0225", "Watermelon", "Fruit / Purée", [], ""],
    ["ING-0226", "Cherry Bitters", "Bitters", [], ""],
    ["ING-0227", "Carrot Purée with Blanco Vermouth", "House Preparation", [], "Composite house preparation; carrot-to-vermouth ratio is not recorded."],
    ["ING-0228", "Opera White Amaretto", "Liqueur", [], ""],
    ["ING-0229", "Browned Butter Tincture", "Tincture", [], ""],
    ["ING-0230", "Dry Red Wine", "Wine", [], ""],
    ["ING-0231", "Fig Syrup", "Syrup / Cordial", [], ""],
    ["ING-0232", "Fruitful Mission Fig", "Syrup / Cordial", [], ""],
    ["ING-0233", "Black Walnut Bitters", "Bitters", [], ""],
    ["ING-0234", "Clear ice with pea-sized feta piece and a few drops feta brine", "House Preparation", [], ""],
    ["ING-0235", "Lagavulin 8", "Whiskey", [], ""],
    ["ING-0236", "Cherry Heering", "Liqueur", [], ""],
    ["ING-0237", "Pink Gin", "Gin", [], ""],
    ["ING-0238", "Lavender Syrup", "Syrup / Cordial", [], ""],
    ["ING-0239", "Greek Coffee Cordial", "Syrup / Cordial", [], ""],
    ["ING-0240", "Whole Egg", "Egg / Dairy", [], ""],
    ["ING-0241", "Mixed Berry Purée", "Fruit / Purée", [], ""],
    ["ING-0242", "Malfy Grapefruit Gin", "Gin", [], ""],
    ["ING-0243", "Quince Cordial", "Syrup / Cordial", [], ""],
    ["ING-0244", "Vanilla Syrup", "Syrup / Cordial", [], ""],
    ["ING-0245", "Light Cream", "Egg / Dairy", [], ""],
    ["ING-0246", "Pear Liqueur", "Liqueur", [], ""],
    ["ING-0247", "Chip Dry White Port", "Fortified Wine", [], ""]
  ];
  const EXISTING_ALIASES = {
  "ING-0004": [
    "JUJU BEE / Red & Raw",
    "JUJU BEE Tincture",
    "JUJU BEE tincture"
  ],
  "ING-0005": [
    "Feta brine + lactic acid ice"
  ],
  "ING-0008": [
    "Honey syrup"
  ],
  "ING-0009": [
    "Stray Dog Greek Gin"
  ],
  "ING-0015": [
    "Elderflower liqueur"
  ],
  "ING-0016": [
    "Sarti"
  ],
  "ING-0019": [
    "Pink grapefruit juice"
  ],
  "ING-0020": [
    "Fresh lemon juice"
  ],
  "ING-0021": [
    "Fresh lime juice",
    "Lime Juice"
  ]
};
  REFERENCES.forEach(([id, name, category, aliases, detail]) => {
    DATA.ingredients.push({
      id, name, category, aliases, recordStatus:'reference', region:'Not recorded',
      roles:[], flavors:[], aroma:[], texture:[], vector:null,
      notes:detail || 'Recorded in cocktail recipes. Sensory profile and product or preparation details have not been encoded.',
      pairings:[], substitutes:[], cautions:[],
      provenance:'Flavor Atlas recipe specifications; ingredient identity only'
    });
  });
  DATA.ingredients.forEach(ingredient => {
    ingredient.aliases = [...new Set([...(ingredient.aliases || []), ...(EXISTING_ALIASES[ingredient.id] || [])])];
  });

  // Explicit label-to-ID decisions. Alternative and combined rows preserve recipe meaning.
  const BINDINGS = [
    ["veda mushroom liqueur", "single", ["ING-0001"]],
    ["vermouth di torino", "single", ["ING-0002"]],
    ["amaro nonino", "single", ["ING-0003"]],
    ["juju bee tincture", "single", ["ING-0004"]],
    ["feta brine + lactic acid ice", "single", ["ING-0005"]],
    ["stray dog greek gin", "single", ["ING-0009"]],
    ["lillet blanc", "single", ["ING-0013"]],
    ["italicus", "single", ["ING-0014"]],
    ["elderflower liqueur", "single", ["ING-0015"]],
    ["pink grapefruit juice", "single", ["ING-0019"]],
    ["fresh lemon juice", "single", ["ING-0020"]],
    ["umeshu bitters", "single", ["ING-0025"]],
    ["saline", "single", ["ING-0026"]],
    ["cucumber juice", "single", ["ING-0027"]],
    ["fresh lime juice", "single", ["ING-0021"]],
    ["simple syrup", "single", ["ING-0028"]],
    ["grey goose berry rouge", "single", ["ING-0029"]],
    ["triple sec", "single", ["ING-0030"]],
    ["monkey 47 gin", "single", ["ING-0031"]],
    ["cocchi americano", "single", ["ING-0032"]],
    ["amaro montenegro", "single", ["ING-0033"]],
    ["orange bitters", "single", ["ING-0034"]],
    ["metaxa 7 or 12 star", "alternative", ["ING-0035", "ING-0012"]],
    ["honey syrup", "single", ["ING-0008"]],
    ["peychaud's bitters", "single", ["ING-0036"]],
    ["mandarin orange bitters", "single", ["ING-0037"]],
    ["ouzo", "single", ["ING-0038"]],
    ["suntory toki", "single", ["ING-0039"]],
    ["grapefruit bitters", "single", ["ING-0040"]],
    ["cognac", "single", ["ING-0041"]],
    ["brown crème de cacao", "single", ["ING-0042"]],
    ["fresh cream", "single", ["ING-0043"]],
    ["bitter campari", "single", ["ING-0044"]],
    ["sweet red vermouth", "single", ["ING-0045"]],
    ["soda water", "single", ["ING-0046"]],
    ["gin", "single", ["ING-0047"]],
    ["apricot brandy", "single", ["ING-0048"]],
    ["calvados", "single", ["ING-0049"]],
    ["maraschino luxardo", "single", ["ING-0050"]],
    ["crème de violette", "single", ["ING-0051"]],
    ["white rum", "single", ["ING-0052"]],
    ["bourbon or rye whiskey", "alternative", ["ING-0053", "ING-0054"]],
    ["brandy", "single", ["ING-0055"]],
    ["curaçao", "single", ["ING-0056"]],
    ["aromatic bitters", "single", ["ING-0057"]],
    ["old tom gin", "single", ["ING-0058"]],
    ["raspberry syrup", "single", ["ING-0059"]],
    ["egg white", "single", ["ING-0060"]],
    ["white cuban rum", "single", ["ING-0061"]],
    ["superfine sugar", "single", ["ING-0062"]],
    ["dry vermouth", "single", ["ING-0063"]],
    ["london dry gin", "single", ["ING-0064"]],
    ["fernet", "single", ["ING-0065"]],
    ["green chartreuse", "single", ["ING-0066"]],
    ["rye whiskey", "single", ["ING-0054"]],
    ["angostura bitters", "single", ["ING-0067"]],
    ["fresh pineapple juice", "single", ["ING-0068"]],
    ["grenadine syrup", "single", ["ING-0069"]],
    ["dry gin", "single", ["ING-0070"]],
    ["fresh orange juice", "single", ["ING-0071"]],
    ["absinthe", "single", ["ING-0072"]],
    ["sugar", "single", ["ING-0073"]],
    ["water", "single", ["ING-0074"]],
    ["jamaican rum", "single", ["ING-0075"]],
    ["lime juice", "single", ["ING-0021"]],
    ["sugar cane juice", "single", ["ING-0076"]],
    ["red tawny port", "single", ["ING-0077"]],
    ["egg yolk", "single", ["ING-0078"]],
    ["sugar syrup", "single", ["ING-0028"]],
    ["cream", "single", ["ING-0079"]],
    ["orange flower water", "single", ["ING-0080"]],
    ["vanilla extract", "single", ["ING-0081"]],
    ["sweet vermouth", "single", ["ING-0082"]],
    ["cherry brandy luxardo", "single", ["ING-0083"]],
    ["scotch whisky", "single", ["ING-0084"]],
    ["drambuie", "single", ["ING-0085"]],
    ["white crème de menthe", "single", ["ING-0086"]],
    ["bénédictine", "single", ["ING-0087"]],
    ["bourbon whiskey", "single", ["ING-0053"]],
    ["egg white (optional)", "single", ["ING-0060"]],
    ["prosecco", "single", ["ING-0088"]],
    ["white peach purée", "single", ["ING-0089"]],
    ["vodka", "single", ["ING-0090"]],
    ["coffee liqueur", "single", ["ING-0091"]],
    ["tomato juice", "single", ["ING-0092"]],
    ["worcestershire sauce", "single", ["ING-0093"]],
    ["tabasco, celery salt, pepper", "combined", ["ING-0094", "ING-0095", "ING-0096"]],
    ["cachaça", "single", ["ING-0097"]],
    ["lime, cut into wedges", "single", ["ING-0098"]],
    ["white cane sugar", "single", ["ING-0099"]],
    ["chilled champagne", "single", ["ING-0100"]],
    ["grand marnier (optional)", "single", ["ING-0101"]],
    ["cointreau", "single", ["ING-0102"]],
    ["vodka citron", "single", ["ING-0103"]],
    ["cranberry juice", "single", ["ING-0104"]],
    ["cola", "single", ["ING-0105"]],
    ["champagne", "single", ["ING-0100"]],
    ["amaretto", "single", ["ING-0106"]],
    ["white crème de cacao", "single", ["ING-0107"]],
    ["green crème de menthe", "single", ["ING-0108"]],
    ["rum", "single", ["ING-0109"]],
    ["grapefruit juice", "single", ["ING-0110"]],
    ["ginger ale", "single", ["ING-0111"]],
    ["irish whiskey", "single", ["ING-0112"]],
    ["hot coffee", "single", ["ING-0113"]],
    ["fresh cream, chilled", "single", ["ING-0043"]],
    ["dry white wine", "single", ["ING-0114"]],
    ["crème de cassis", "single", ["ING-0115"]],
    ["tequila", "single", ["ING-0116"]],
    ["amber jamaican rum", "single", ["ING-0117"]],
    ["martinique molasses rhum", "single", ["ING-0118"]],
    ["orange curaçao", "single", ["ING-0119"]],
    ["orgeat syrup", "single", ["ING-0120"]],
    ["100% agave tequila", "single", ["ING-0121"]],
    ["fresh mint", "single", ["ING-0122"]],
    ["powdered sugar", "single", ["ING-0123"]],
    ["mint", "single", ["ING-0122"]],
    ["ginger beer", "single", ["ING-0124"]],
    ["coconut cream", "single", ["ING-0125"]],
    ["pisco", "single", ["ING-0126"]],
    ["cynar", "single", ["ING-0127"]],
    ["peach schnapps", "single", ["ING-0128"]],
    ["cherry sangue morlacco", "single", ["ING-0129"]],
    ["dom bénédictine", "single", ["ING-0087"]],
    ["jamaican dark rum", "single", ["ING-0130"]],
    ["gold puerto rican rum", "single", ["ING-0131"]],
    ["demerara rum", "single", ["ING-0132"]],
    ["falernum", "single", ["ING-0133"]],
    ["donn's mix", "single", ["ING-0134"]],
    ["pernod", "single", ["ING-0135"]],
    ["crème de mûre", "single", ["ING-0136"]],
    ["cuban aguardiente", "single", ["ING-0137"]],
    ["raw honey", "single", ["ING-0138"]],
    ["goslings rum", "single", ["ING-0139"]],
    ["gold jamaican rum", "single", ["ING-0140"]],
    ["cuban rum", "single", ["ING-0141"]],
    ["passion fruit syrup", "single", ["ING-0142"]],
    ["kahlúa", "single", ["ING-0143"]],
    ["espresso", "single", ["ING-0144"]],
    ["fernet branca", "single", ["ING-0145"]],
    ["raspberry liqueur", "single", ["ING-0146"]],
    ["italian basil", "single", ["ING-0147"]],
    ["grand marnier", "single", ["ING-0101"]],
    ["havana club ron profundo", "single", ["ING-0148"]],
    ["havana club ron smoky", "single", ["ING-0149"]],
    ["frangelico", "single", ["ING-0150"]],
    ["passion fruit puree", "single", ["ING-0151"]],
    ["ginger", "single", ["ING-0152"]],
    ["espadin mezcal", "single", ["ING-0153"]],
    ["jamaica overproof white rum", "single", ["ING-0154"]],
    ["egg white, optional", "single", ["ING-0060"]],
    ["blackstrap rum", "single", ["ING-0155"]],
    ["campari", "single", ["ING-0044"]],
    ["pineapple juice", "single", ["ING-0068"]],
    ["demerara sugar syrup", "single", ["ING-0156"]],
    ["peach brandy", "single", ["ING-0157"]],
    ["honey mix", "single", ["ING-0158"]],
    ["mint leaves", "single", ["ING-0122"]],
    ["pineapple chunks", "single", ["ING-0159"]],
    ["mezcal", "single", ["ING-0160"]],
    ["yellow chartreuse", "single", ["ING-0018"]],
    ["aperol", "single", ["ING-0161"]],
    ["rye whiskey or bourbon", "alternative", ["ING-0053", "ING-0054"]],
    ["red wine, shiraz or malbec", "alternative", ["ING-0162", "ING-0163"]],
    ["aged rum", "single", ["ING-0164"]],
    ["brut champagne or prosecco", "alternative", ["ING-0165", "ING-0088"]],
    ["salt", "single", ["ING-0166"]],
    ["pink grapefruit soda", "single", ["ING-0167"]],
    ["blended scotch whisky", "single", ["ING-0168"]],
    ["lagavulin 16", "single", ["ING-0169"]],
    ["fresh ginger", "single", ["ING-0152"]],
    ["cloves", "single", ["ING-0170"]],
    ["vanilla vodka", "single", ["ING-0171"]],
    ["passion fruit liqueur", "single", ["ING-0172"]],
    ["vanilla sugar", "single", ["ING-0173"]],
    ["sparkling wine", "single", ["ING-0174"]],
    ["amontillado sherry", "single", ["ING-0175"]],
    ["palo cortado", "single", ["ING-0176"]],
    ["orange", "single", ["ING-0177"]],
    ["lemon", "single", ["ING-0178"]],
    ["elderflower cordial", "single", ["ING-0179"]],
    ["red chili pepper", "single", ["ING-0180"]],
    ["cognac or brandy", "alternative", ["ING-0041", "ING-0055"]],
    ["rhum martinique agricole", "single", ["ING-0181"]],
    ["blended aged rum", "single", ["ING-0182"]],
    ["allspice dram", "single", ["ING-0183"]],
    ["agave nectar", "single", ["ING-0184"]],
    ["white smooth grappa", "single", ["ING-0185"]],
    ["chamomile honey mix", "single", ["ING-0186"]],
    ["chamomile cordial", "single", ["ING-0187"]],
    ["mastiha", "single", ["ING-0188"]],
    ["blood orange juice", "single", ["ING-0189"]],
    ["orange liqueur", "single", ["ING-0190"]],
    ["stoli citrus", "single", ["ING-0191"]],
    ["tsipouro", "single", ["ING-0011"]],
    ["olive brine", "single", ["ING-0192"]],
    ["hot sauce", "single", ["ING-0193"]],
    ["dried oregano", "single", ["ING-0194"]],
    ["stray dog gin", "single", ["ING-0009"]],
    ["white bitter rouge", "single", ["ING-0195"]],
    ["metaxa 7 star", "single", ["ING-0035"]],
    ["sarti", "single", ["ING-0016"]],
    ["limoncello", "single", ["ING-0017"]],
    ["thyme blossom tincture", "single", ["ING-0196"]],
    ["foro amaro", "single", ["ING-0197"]],
    ["velvet falernum", "single", ["ING-0198"]],
    ["orgeat", "single", ["ING-0120"]],
    ["juju bee / red & raw", "single", ["ING-0004"]],
    ["skinos mastiha", "single", ["ING-0199"]],
    ["elixir liqueur", "single", ["ING-0200"]],
    ["del maguey vida", "single", ["ING-0201"]],
    ["fruitful blue raspberry lemonade", "single", ["ING-0202"]],
    ["metaxa 12 star", "single", ["ING-0012"]],
    ["knob creek bourbon", "single", ["ING-0203"]],
    ["starlight applejack", "single", ["ING-0204"]],
    ["bauchant", "single", ["ING-0205"]],
    ["mavrodaphne", "single", ["ING-0006"]],
    ["peach bitters", "single", ["ING-0206"]],
    ["lychee liqueur", "single", ["ING-0023"]],
    ["soursop nectar", "single", ["ING-0022"]],
    ["lychee syrup", "single", ["ING-0207"]],
    ["grenadine", "single", ["ING-0208"]],
    ["metaxa", "single", ["ING-0209"]],
    ["concentrated nescafé frappé", "single", ["ING-0210"]],
    ["chocolate bitters", "single", ["ING-0211"]],
    ["cadilla açaí liqueur", "single", ["ING-0212"]],
    ["feta-brine ice", "single", ["ING-0213"]],
    ["dark crème de cacao", "single", ["ING-0042"]],
    ["mastiha antica", "single", ["ING-0010"]],
    ["pistachio orgeat", "single", ["ING-0214"]],
    ["heavy cream", "single", ["ING-0215"]],
    ["thyme blossom honey syrup", "single", ["ING-0216"]],
    ["fresh espresso", "single", ["ING-0144"]],
    ["vanilla gelato", "single", ["ING-0217"]],
    ["galliano", "single", ["ING-0218"]],
    ["prickly pear", "single", ["ING-0219"]],
    ["orange juice", "single", ["ING-0071"]],
    ["cream cheese tincture", "single", ["ING-0220"]],
    ["black cherry tincture", "single", ["ING-0221"]],
    ["soho lychee liqueur", "single", ["ING-0222"]],
    ["umeshu tincture", "single", ["ING-0223"]],
    ["pineapple syrup", "single", ["ING-0224"]],
    ["watermelon", "single", ["ING-0225"]],
    ["cherry bitters", "single", ["ING-0226"]],
    ["orange blossom water", "single", ["ING-0080"]],
    ["carrot purée with blanco vermouth", "single", ["ING-0227"]],
    ["montenegro", "single", ["ING-0033"]],
    ["opera white amaretto", "single", ["ING-0228"]],
    ["browned butter tincture", "single", ["ING-0229"]],
    ["dry red wine", "single", ["ING-0230"]],
    ["fig syrup or fruitful mission fig", "alternative", ["ING-0231", "ING-0232"]],
    ["black walnut bitters", "single", ["ING-0233"]],
    ["clear ice with pea-sized feta piece and a few drops feta brine", "single", ["ING-0234"]],
    ["lagavulin 8", "single", ["ING-0235"]],
    ["cherry heering", "single", ["ING-0236"]],
    ["pink gin", "single", ["ING-0237"]],
    ["lavender syrup", "single", ["ING-0238"]],
    ["greek coffee cordial", "single", ["ING-0239"]],
    ["whole egg", "single", ["ING-0240"]],
    ["mixed berry purée", "single", ["ING-0241"]],
    ["malfy grapefruit gin", "single", ["ING-0242"]],
    ["quince cordial", "single", ["ING-0243"]],
    ["vanilla syrup", "single", ["ING-0244"]],
    ["light cream", "single", ["ING-0245"]],
    ["applejack", "single", ["ING-0024"]],
    ["pear liqueur", "single", ["ING-0246"]],
    ["chip dry white port", "single", ["ING-0247"]]
  ];
  const byLabel = new Map(BINDINGS.map(([label, kind, ingredientIds]) => [label, {kind, ingredientIds}]));
  DATA.resolveRecipeIngredient = label => {
    const match = byLabel.get(normalize(label));
    return match ? {kind:match.kind, ingredientIds:[...match.ingredientIds]} : {kind:'unresolved', ingredientIds:[]};
  };
  DATA.cocktails.forEach(c => {
    c.ingredientRefs = (c.specs || []).map(([measure, label], specIndex) => ({
      specIndex, measure, label, ...DATA.resolveRecipeIngredient(label)
    }));
  });
  DATA.ingredients.forEach(ingredient => {
    ingredient.usedIn = DATA.cocktails.filter(c => c.ingredientRefs.some(r => r.ingredientIds.includes(ingredient.id))).map(c => c.id);
    if (ingredient.recordStatus === 'reference') {
      // Only reuse roles explicitly recorded for this individual ingredient in a linked recipe.
      ingredient.recipeRoles = DATA.cocktails.filter(c => ingredient.usedIn.includes(c.id)).flatMap(c =>
        (c.functions || []).filter(([label]) => {
          const ref = DATA.resolveRecipeIngredient(label);
          return ref.kind === 'single' && ref.ingredientIds.length === 1 && ref.ingredientIds[0] === ingredient.id;
        }).map(([, role]) => ({cocktailId:c.id, role}))
      );
      ingredient.roles = [...new Set(ingredient.recipeRoles.map(r => r.role))];
    }
  });
  const refs = DATA.cocktails.flatMap(c => c.ingredientRefs.map(r => ({cocktailId:c.id, ...r})));
  const ids = new Set(DATA.ingredients.map(i => i.id));
  DATA.ingredientAudit = {
    recipeCount:DATA.cocktails.filter(c => c.specs?.length).length,
    ingredientCount:DATA.ingredients.length,
    specRowCount:refs.length,
    linkedRowCount:refs.filter(r => r.ingredientIds.length && r.ingredientIds.every(id => ids.has(id))).length,
    unresolved:refs.filter(r => !r.ingredientIds.length || r.ingredientIds.some(id => !ids.has(id)))
  };
})();
